import {NextRequest,NextResponse} from 'next/server';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {authorize,authenticated,equal,env,sessionToken} from '@/lib/security';
import {listCases,getCase,saveCase,saveKey,loadKey,audit,withCaseLock} from '@/lib/store';
import {dispatch,poll,stop,cloud} from '@/lib/cloud';
import {countries,validatePortal} from '@/lib/countries';
import type {VisaCase} from '@/types/visa';
export const runtime='nodejs';export const dynamic='force-dynamic';export const maxDuration=60;
const Create=z.object({action:z.literal('create'),country:z.enum(['au','rs','tr','sg','ru','my','sa','bh']),applicantName:z.string().trim().min(1).max(120),visaType:z.string().trim().min(1).max(120),command:z.string().trim().min(5).max(2000),portalUrl:z.string().url()});
function json(value:unknown,status=200){return NextResponse.json(value,{status,headers:{'Cache-Control':'no-store'}});}
function failed(e:unknown){const code=e instanceof z.ZodError?'INVALID_INPUT':e instanceof Error&&/^[A-Z_]+$/.test(e.message)?e.message:'SERVICE_UNAVAILABLE';const s=(e as {statusCode?:number}).statusCode;return json({error:code,...(s?{providerStatus:s}:{})},code==='UNAUTHORIZED'?401:code==='FORBIDDEN'?403:code==='CASE_BUSY'?409:code==='INVALID_INPUT'||code==='INVALID_PORTAL'?400:503);}
export async function GET(req:NextRequest){try{if(!authenticated(req))return json({authenticated:false,databaseConfigured:Boolean(process.env.DATABASE_URL),cloudConfigured:Boolean(process.env.BROWSER_USE_API_KEY),pythonConfigured:Boolean(process.env.PYTHON_BACKEND_URL)});authorize(req);if(!process.env.DATABASE_URL)return json({authenticated:true,cases:[],setupRequired:true});return json({authenticated:true,cases:await listCases(),setupRequired:false,pythonConfigured:Boolean(process.env.PYTHON_BACKEND_URL)});}catch(e){return failed(e);}}
export async function POST(req:NextRequest){try{const origin=req.headers.get('origin');if(origin&&origin!==req.nextUrl.origin)throw new Error('FORBIDDEN');if(Number(req.headers.get('content-length')??0)>24000)throw new Error('INVALID_INPUT');const raw=await req.text();if(Buffer.byteLength(raw)>24000)throw new Error('INVALID_INPUT');const body=JSON.parse(raw);const action=z.string().parse(body.action);
if(action==='login'){const token=z.string().max(256).parse(body.token);if(env('DASHBOARD_ACCESS_TOKEN').length<32||!equal(token,env('DASHBOARD_ACCESS_TOKEN')))throw new Error('UNAUTHORIZED');const response=json({authenticated:true});response.cookies.set('velovisa_session',sessionToken(),{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',path:'/',maxAge:28800});return response;}
authorize(req);
if(action==='logout'){const r=json({ok:true});r.cookies.delete('velovisa_session');return r;}
if(action==='key'){const key=z.string().regex(/^bu_/).max(256).parse(body.key);const {BrowserUse}=await import('browser-use-sdk/v4');await new BrowserUse({apiKey:key,maxRetries:0}).runs.list({limit:1});await saveKey(key);await audit('integration.key.updated');return json({connected:true});}
if(action==='connection'){await (await cloud()).runs.list({limit:1});const r=await fetch('https://api.browser-use.com/api/v2/billing/account',{headers:{'X-Browser-Use-API-Key':await loadKey()},cache:'no-store',signal:AbortSignal.timeout(15000)});const account=r.ok?await r.json():null;return json({connected:true,account,pythonConfigured:Boolean(process.env.PYTHON_BACKEND_URL)});}
if(action==='create'){const input=Create.parse(body);if(!countries[input.country])throw new Error('INVALID_INPUT');validatePortal(input.portalUrl,env('VISA_PORTAL_HOSTS'));const now=new Date().toISOString();const c:VisaCase={id:randomUUID(),...input,status:'Idle',createdAt:now,updatedAt:now,documents:[],checklist:{}};await saveCase(c);await audit('case.created',c.id);return json({case:c});}
const id=z.string().uuid().parse(body.id);
return await withCaseLock(id,async()=>{const c=await getCase(id);
if(action==='checklist'){const key=z.string().parse(body.key);if(!countries[c.country].rules.some(r=>r.id===key))throw new Error('INVALID_INPUT');c.checklist[key]=z.boolean().parse(body.value);await saveCase(c);await audit('case.checklist.reviewed',id);return json({case:c});}
if(action==='dispatch'||action==='resume'){if(body.confirmed!==true)throw new Error('APPROVAL_REQUIRED');if(c.status==='Running'||c.status==='Dispatch Unknown')throw new Error('CASE_BUSY');if(action==='dispatch'&&c.run)throw new Error('NEW_CASE_REQUIRED');if(action==='resume'&&!['OTP Required','Review Required'].includes(c.status))throw new Error('NO_CHECKPOINT');const otp=body.otp===undefined?undefined:z.string().regex(/^\d{6}$/).parse(body.otp);if(c.status==='OTP Required'&&!otp)throw new Error('OTP_REQUIRED');await audit('cloud.dispatch.requested',id);c.status='Dispatch Unknown';await saveCase(c);try{await dispatch(c,otp);await saveCase(c);await audit('cloud.dispatched',id);}catch{c.status='Dispatch Unknown';c.error='RECONCILE_CLOUD_BEFORE_RETRY';await saveCase(c);throw new Error('RECONCILE_CLOUD_BEFORE_RETRY');}}
else if(action==='poll'){await poll(c);await saveCase(c);}
else if(action==='stop'){if(body.confirmed!==true)throw new Error('APPROVAL_REQUIRED');await audit('cloud.stop.requested',id);await stop(c);await saveCase(c);await audit('cloud.stopped',id);}
else if(action==='snapshot'){if(body.confirmed!==true)throw new Error('APPROVAL_REQUIRED');validatePortal(c.portalUrl,env('VISA_PORTAL_HOSTS'));const base=env('PYTHON_BACKEND_URL');const r=await fetch(base.replace(/\/$/,'')+'/preview',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+env('PYTHON_SERVICE_TOKEN')},body:JSON.stringify({url:c.portalUrl,country:c.country}),signal:AbortSignal.timeout(45000)});if(!r.ok)throw new Error('PYTHON_PREVIEW_FAILED');await audit('playwright.preview.completed',id);return json({preview:await r.json()});}
else throw new Error('INVALID_INPUT');return json({case:c});});}catch(e){return failed(e);}}
