'use client';
import {useState,useEffect,useRef} from 'react';
import {Bot,Globe2,Menu,FolderOpen,KeyRound,Send,Plus,ShieldCheck,Printer,RefreshCw,X,Upload} from 'lucide-react';
import VisaCaseQueue from '@/components/VisaCaseQueue';
import LiveBrowserView from '@/components/LiveBrowserView';
import JsonViewer from '@/components/JsonViewer';
import {countries,draftLetter} from '@/lib/countries';
import type {Country,Language,VisaCase} from '@/types/visa';
type Overview={authenticated:boolean;cases?:VisaCase[];setupRequired?:boolean;pythonConfigured?:boolean};
type Connection={connected:boolean;account?:{totalCreditsBalanceUsd?:number;concurrentSessionLimit?:number;activeSessionCount?:number;rateLimit?:number};pythonConfigured?:boolean};
type Tab='chat'|'cases'|'cloud'|'settings';
const translations:Record<string,[string,string]>={UNAUTHORIZED:['Sign in with your agency access token.','এজেন্সির অ্যাক্সেস টোকেন দিয়ে লগইন করুন।'],SETUP_REQUIRED:['Configure the database and server environment first.','আগে ডেটাবেস ও সার্ভারের পরিবেশ সেটআপ করুন।'],SERVICE_UNAVAILABLE:['Service unavailable; check server setup and provider status.','সেবা অনুপলব্ধ; সার্ভারের সেটআপ ও প্রদানকারীর অবস্থা যাচাই করুন।'],PORTAL_NOT_ALLOWED:['Add the exact authorized hostname to VISA_PORTAL_HOSTS.','অনুমোদিত হোস্টনেম VISA_PORTAL_HOSTS-এ যোগ করুন।'],RECONCILE_CLOUD_BEFORE_RETRY:['Cloud dispatch is uncertain. Check the provider dashboard before retrying.','ক্লাউড রান নিশ্চিত নয়। আবার চেষ্টা করার আগে প্রদানকারীর ড্যাশবোর্ড যাচাই করুন।'],EXTRACTION_UNAVAILABLE:['Configure the Python document service first.','আগে Python নথি সেবা সেটআপ করুন।'],INVALID_INPUT:['Complete all required fields.','প্রয়োজনীয় সব তথ্য পূরণ করুন।'],CASE_BUSY:['This case is busy. Please wait before retrying.','কেসে কাজ চলছে। আবার চেষ্টা করার আগে অপেক্ষা করুন।'],NO_CHECKPOINT:['No pending human checkpoint exists.','মানব পর্যালোচনার কোনো অপেক্ষমাণ ধাপ নেই।'],KEY_SAVE_CONFIRM:['Save this API key encrypted on the server?','API কী সার্ভারে এনক্রিপ্ট করে সংরক্ষণ করবেন?']};
export default function Home(){
 const [lang,setLang]=useState<Language>('en'),[tab,setTab]=useState<Tab>('chat'),[mobile,setMobile]=useState(false);
 const t=(en:string,bn:string)=>lang==='bn'?bn:en;
 const [overview,setOverview]=useState<Overview>({authenticated:false}),[connection,setConnection]=useState<Connection>();
 const [cases,setCases]=useState<VisaCase[]>([]),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [token,setToken]=useState(''),[key,setKey]=useState(''),[newCase,setNewCase]=useState(false);
 const [country,setCountry]=useState<Country>('sg'),[name,setName]=useState(''),[visaType,setVisaType]=useState('Employment Pass'),[portal,setPortal]=useState(countries.sg.portal),[command,setCommand]=useState('');
 const [view,setView]=useState<'form'|'checklist'|'letter'>('checklist'),[snapshot,setSnapshot]=useState<unknown>();
 const [messages,setMessages]=useState<{role:string;text:string}[]>([]);
 const current=cases.find(c=>c.id===selected),profile=countries[current?.country??country];
 const state=useRef({cases,busy,selected});state.current={cases,busy,selected};
 async function request<T>(body?:unknown):Promise<T>{const response=await fetch('/api/visa-agent',{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const data=await response.json();if(!response.ok){const e=new Error(data.error??'SERVICE_UNAVAILABLE') as Error&{delay?:number};const retry=response.headers.get('Retry-After');e.delay=retry&&/^\d+$/.test(retry)?Math.max(5000,Number(retry)*1000):10000;throw e;}return data;}
 async function refresh(){const data=await request<Overview>();setOverview(data);if(data.cases){setCases(data.cases);setSelected(old=>old||data.cases?.[0]?.id||'');}}
 function merge(item:VisaCase){setCases(old=>old.some(c=>c.id===item.id)?old.map(c=>c.id===item.id?item:c):[item,...old]);}
 async function act(fn:()=>Promise<void>){if(state.current.busy)return;setBusy(true);state.current.busy=true;setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'SERVICE_UNAVAILABLE');}finally{setBusy(false);state.current.busy=false;}}
 useEffect(()=>{void refresh().catch(()=>setError('SERVICE_UNAVAILABLE'));},[]);
 useEffect(()=>{document.documentElement.lang=lang;},[lang]);
 useEffect(()=>{if(!overview.authenticated)return;let stopped=false;let timer:ReturnType<typeof setTimeout>;async function tick(){let delay=5000;if(!state.current.busy){for(const item of state.current.cases){if(stopped)break;if(item.status!=='Running')continue;try{const out=await request<{case:VisaCase}>({action:'poll',id:item.id});if(!stopped)merge(out.case);if(out.case.run?.hasMore)delay=1000;}catch(e){if(!stopped)setError(e instanceof Error?e.message:'SERVICE_UNAVAILABLE');delay=(e as Error&{delay?:number}).delay??10000;break;}}}if(!stopped)timer=setTimeout(()=>void tick(),delay);}timer=setTimeout(()=>void tick(),5000);return()=>{stopped=true;clearTimeout(timer);};},[overview.authenticated]);
 function detect(text:string){if(/[\u0980-\u09ff]/.test(text)||/\b(amar|apnar|koren|korun|bangla|lagbe|chai|dorkar)\b/i.test(text))setLang('bn');}
 async function login(event:React.FormEvent){event.preventDefault();await act(async()=>{await request({action:'login',token});setToken('');await refresh();});}
 async function create(event:React.FormEvent){event.preventDefault();detect(command);await act(async()=>{const out=await request<{case:VisaCase}>({action:'create',applicantName:name,country,visaType,portalUrl:portal,command:command.trim()||'Research current official requirements and prepare my document checklist.'});merge(out.case);setSelected(out.case.id);setNewCase(false);setTab('cases');});}
 async function run(item:VisaCase,objective?:string){if(!window.confirm(t(`Start a billable Cloud research run for ${item.applicantName}? No visa submission or payment is authorized.`,` ${item.applicantName}-এর জন্য অর্থপ্রদ ক্লাউড গবেষণা শুরু করবেন? ভিসা জমা বা পেমেন্টের অনুমতি নয়।`)))return;const out=await request<{case:VisaCase}>({action:'dispatch',id:item.id,confirmed:true,...(objective?{command:objective}:{})});merge(out.case);setTab('cloud');setMessages(old=>[...old,{role:'assistant',text:t('Cloud run started. Watch the live browser and human checkpoints.','ক্লাউড রান শুরু হয়েছে। লাইভ ব্রাউজার ও মানব পর্যালোচনার ধাপ দেখুন।')}]);}
 async function send(event:React.FormEvent){event.preventDefault();if(command.trim().length<5)return;detect(command);setMessages(old=>[...old,{role:'user',text:command}]);if(!current){setNewCase(true);return;}await act(()=>run(current,command));}
 async function resume(otp?:string){if(!current)return;await act(async()=>{if(!window.confirm(t('Start a billable continuation and verify the authorized OTP if supplied?','অর্থপ্রদ পরবর্তী রান এবং প্রদত্ত অনুমোদিত OTP যাচাই শুরু করবেন?')))return;const out=await request<{case:VisaCase}>({action:'resume',id:current.id,otp,confirmed:true});merge(out.case);});}
 async function stop(){if(!current)return;await act(async()=>{if(!window.confirm(t('Cancel this run and stop its managed browsers?','রান বাতিল ও ক্লাউড ব্রাউজার বন্ধ করবেন?')))return;const out=await request<{case:VisaCase}>({action:'stop',id:current.id,confirmed:true});merge(out.case);});}
 async function upload(file:File){if(!current)return;await act(async()=>{const form=new FormData();form.set('id',current.id);form.set('file',file);const response=await fetch('/api/documents',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw new Error(data.error??'EXTRACTION_UNAVAILABLE');merge(data.case);});}
 const passportCandidates=new Set(current?.documents.flatMap(d=>d.passportNumbers.map(v=>v.toUpperCase()))??[]);
 const nav:Record<Tab,string>={chat:t('AI Assistance Chat','AI সহায়তা চ্যাট'),cases:t('Visa Case Workspace','ভিসা কেস ওয়ার্কস্পেস'),cloud:t('Browser Use Cloud v4','Browser Use ক্লাউড v4'),settings:t('Connections & API keys','সংযোগ ও API কী')};
 const errorText=translations[error]?.[lang==='bn'?1:0]??(error?t(`Request failed (${error}). Review server configuration.`,`অনুরোধ ব্যর্থ (${error})। সার্ভারের সেটআপ যাচাই করুন।`):'');
 return <main className="min-h-screen bg-white text-zinc-900"><header className="no-print safe-top sticky top-0 z-20 border-b border-zinc-200 bg-white"><div className="flex flex-wrap items-center justify-between gap-3 px-4 py-4 lg:px-7"><div className="flex items-center gap-3"><button aria-label={t('Navigation','নেভিগেশন')} className="lg:hidden" onClick={()=>setMobile(!mobile)}><Menu size={20}/></button><ShieldCheck size={25}/><div><h1 className="font-semibold tracking-tight">VeloVisa AI</h1><p className="text-xs text-zinc-500">{t('Visa Intelligence Engine','ভিসা ইন্টেলিজেন্স ইঞ্জিন')}</p></div></div><div className="flex items-center gap-3"><span className="badge hidden sm:inline-flex">{connection?.connected?t('Cloud API v4 Active','ক্লাউড API v4 সক্রিয়'):t('Cloud not verified','ক্লাউড যাচাই হয়নি')}</span><button className="btn" onClick={()=>setLang(lang==='en'?'bn':'en')}>{lang==='en'?'বাংলা':'English'}</button><button className="btn primary" disabled={!overview.authenticated||overview.setupRequired} onClick={()=>setNewCase(true)}><Plus size={15}/>{t('New case','নতুন কেস')}</button></div></div></header>
 {!overview.authenticated?<div className="mx-auto max-w-lg p-6"><form className="card space-y-4 p-6" onSubmit={login}><KeyRound/><h2 className="text-xl font-semibold">{t('Connect your agency workspace','এজেন্সির ওয়ার্কস্পেস যুক্ত করুন')}</h2><p className="text-sm leading-6 text-zinc-500">{t('Enter DASHBOARD_ACCESS_TOKEN. Browser Use API keys stay server-side.','DASHBOARD_ACCESS_TOKEN দিন। Browser Use API কী সার্ভারেই থাকবে।')}</p><input aria-label={t('Agency access token','এজেন্সির অ্যাক্সেস টোকেন')} className="field" type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)} required/><button className="btn primary" disabled={busy}>{t('Sign in','সাইন ইন')}</button>{errorText&&<p role="alert" className="text-sm text-red-700">{errorText}</p>}<p className="text-xs text-zinc-500">{t('Setup instructions are in the repository README.','সেটআপের নির্দেশনা রিপোজিটরির README-তে রয়েছে।')}</p></form></div>:<div className="flex"><aside className={`no-print ${mobile?'fixed inset-0 z-30 bg-white p-5':'hidden'} safe-bottom w-72 shrink-0 border-r border-zinc-200 lg:sticky lg:top-20 lg:block lg:max-h-[calc(100vh-80px)] lg:overflow-auto lg:p-5`}><button aria-label={t('Close navigation','নেভিগেশন বন্ধ')} className="mb-4 lg:hidden" onClick={()=>setMobile(false)}><X/></button><nav className="space-y-1">{(Object.keys(nav) as Tab[]).map(id=><button key={id} className={`flex w-full items-center gap-2 rounded-lg p-3 text-left text-sm ${tab===id?'bg-zinc-100 font-semibold':'hover:bg-zinc-50'}`} onClick={()=>{setTab(id);setMobile(false);}}>{id==='chat'?<Bot size={16}/>:id==='cases'?<FolderOpen size={16}/>:id==='cloud'?<Globe2 size={16}/>:<KeyRound size={16}/>} {nav[id]}</button>)}</nav><div className="mt-5"><VisaCaseQueue cases={cases} selected={selected} lang={lang} onSelect={id=>{setSelected(id);setMobile(false);}}/></div><div className="mt-5 space-y-2 text-xs text-zinc-500"><p>{t('Provider credits','প্রদানকারীর ক্রেডিট')}: {connection?.account?.totalCreditsBalanceUsd===undefined?'—':`$${connection.account.totalCreditsBalanceUsd.toFixed(2)}`}</p><p>{t('Latest reported run cost','সর্বশেষ রানের রিপোর্টকৃত খরচ')}: {current?.run?.costUsd?`$${current.run.costUsd}`:'—'}</p><a className="block underline" href="https://cloud.browser-use.com" target="_blank" rel="noopener noreferrer">Browser Use Cloud</a><button className="underline" onClick={()=>void act(async()=>{await request({action:'logout'});setOverview({authenticated:false});setCases([]);setMessages([]);setConnection(undefined);})}>{t('Sign out','সাইন আউট')}</button></div></aside>
 <div className="safe-bottom min-w-0 flex-1 p-4 lg:p-7">{errorText&&<div role="alert" className="no-print mb-4 flex justify-between gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800"><span>{errorText}</span><button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}{overview.setupRequired&&<div className="no-print mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{t('Database not configured. Set DATABASE_URL, VAULT_KEY and run the migration before creating cases.','ডেটাবেস সেট করা নেই। কেস তৈরির আগে DATABASE_URL, VAULT_KEY সেট করে মাইগ্রেশন চালান।')}</div>}
 <div className="no-print mb-5 flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold">{nav[tab]}</h2><p className="mt-1 text-xs text-zinc-500">{current?`${current.applicantName} · ${lang==='bn'?profile.bn:profile.name}`:t('Create or select a case','একটি কেস তৈরি বা নির্বাচন করুন')}</p></div><span className="text-xs text-zinc-500">{t('Proxy country requested','অনুরোধকৃত প্রক্সি দেশ')}: {(current?.country??country).toUpperCase()}</span></div>
 {tab==='settings'?<div className="no-print grid gap-5 xl:grid-cols-2"><section className="card space-y-4 p-5"><h3 className="font-semibold">Browser Use Cloud v4</h3><p className="text-sm text-zinc-500">{t('Save and verify a server-side key. It is encrypted in PostgreSQL, not localStorage.','সার্ভারে কী সংরক্ষণ ও যাচাই করুন। এটি PostgreSQL-এ এনক্রিপ্ট করা হয়, localStorage-এ নয়।')}</p><a className="text-sm underline" href="https://cloud.browser-use.com/settings?tab=api-keys&new=1" target="_blank" rel="noopener noreferrer">{t('Create a Cloud API key','ক্লাউড API কী তৈরি করুন')}</a><input aria-label="Browser Use API key" type="password" autoComplete="off" className="field" value={key} onChange={e=>setKey(e.target.value)} placeholder="bu_…"/><div className="flex flex-wrap gap-2"><button className="btn primary" disabled={busy||!key.startsWith('bu_')||overview.setupRequired} onClick={()=>void act(async()=>{if(!window.confirm(t('Verify and save this API key encrypted on the server?','API কী যাচাই করে সার্ভারে এনক্রিপ্ট করে সংরক্ষণ করবেন?')))return;await request({action:'key',key});setKey('');setConnection(await request<Connection>({action:'connection'}));})}>{t('Verify & save key','যাচাই ও কী সংরক্ষণ')}</button><button className="btn" disabled={busy} onClick={()=>void act(async()=>setConnection(await request<Connection>({action:'connection'})))}><RefreshCw size={14}/>{t('Test connection','সংযোগ পরীক্ষা')}</button></div><p className="text-xs text-zinc-500">{t('Credentials from chat should be rotated before use.','চ্যাটে দেওয়া কী ব্যবহারের আগে পরিবর্তন করুন।')}</p>{connection?.connected&&<JsonViewer lang={lang} value={{connected:true,creditsUsd:connection.account?.totalCreditsBalanceUsd??null,concurrentSessionLimit:connection.account?.concurrentSessionLimit??connection.account?.rateLimit??null,activeSessionCount:connection.account?.activeSessionCount??null}}/>}</section><section className="card space-y-4 p-5"><h3 className="font-semibold">Python · LangGraph · Playwright</h3><p className="text-sm leading-6 text-zinc-500">{t('Set PYTHON_BACKEND_URL and PYTHON_SERVICE_TOKEN for document extraction, policy planning and paid read-only Playwright snapshots. A configured URL is not a verified deployment.','নথি সংগ্রহ, নীতিমালা পরিকল্পনা ও অর্থপ্রদ Playwright প্রিভিউর জন্য PYTHON_BACKEND_URL ও PYTHON_SERVICE_TOKEN সেট করুন। URL সেট করা মানেই যাচাইকৃত ডিপ্লয় নয়।')}</p><pre className="overflow-auto rounded-lg border border-zinc-200 p-3 text-xs">pip install --upgrade -r backend/requirements.txt{'\n'}uvicorn backend.main:app --host 0.0.0.0 --port 8000</pre><p className="text-xs leading-5 text-zinc-500">{t('Use the backend Dockerfile for Tesseract and LibreOffice. Restrict access to your Next.js service.','Tesseract ও LibreOffice-এর জন্য ব্যাকএন্ড Dockerfile ব্যবহার করুন। প্রবেশাধিকার আপনার Next.js সেবায় সীমিত রাখুন।')}</p></section></div>:<div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(320px,.9fr)]"><div className="no-print min-w-0 space-y-5">
 {tab==='chat'&&<section className="card flex min-h-[390px] flex-col"><div className="flex-1 space-y-4 p-5"><p className="text-sm leading-6 text-zinc-500">{t('One command starts official-source research and preparation for the selected case. It does not authorize visa submission, booking or payment.','একটি নির্দেশে নির্বাচিত কেসের সরকারি তথ্য গবেষণা ও প্রস্তুতি শুরু হয়। এতে ভিসা জমা, বুকিং বা পেমেন্টের অনুমতি দেওয়া হয় না।')}</p>{messages.map((m,i)=><div key={i} className={`rounded-xl p-3 text-sm leading-6 ${m.role==='user'?'ml-8 bg-zinc-100':'mr-8 border border-zinc-200'}`}>{m.text}</div>)}</div><form className="flex items-end gap-2 border-t border-zinc-200 p-4" onSubmit={send}><textarea aria-label={t('Agent command','এজেন্টের নির্দেশ')} className="field min-h-20" value={command} onChange={e=>setCommand(e.target.value)} placeholder={t('Research current requirements and prepare my checklist…','বর্তমান শর্ত ও নথির তালিকা প্রস্তুত করুন…')}/><button className="btn primary" disabled={busy||command.trim().length<5||overview.setupRequired} aria-label={t('Send command','নির্দেশ পাঠান')}><Send size={17}/></button></form></section>}
 {(tab==='cloud'||tab==='cases')&&<LiveBrowserView item={current} lang={lang} busy={busy} onResume={resume} onStop={stop}/>}
 {current&&<section className="card space-y-3 p-5"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{t('Documents & consistency','নথি ও সামঞ্জস্য')}</h3><label className="btn cursor-pointer"><Upload size={14}/>{t('Upload','আপলোড')}<input type="file" className="hidden" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void upload(file);}}/></label></div><p className="text-xs text-zinc-500">PDF · DOC · DOCX · JPG · PNG · 10 MB</p>{current.documents.map((d,i)=><details key={i} className="rounded-lg border border-zinc-200 p-3"><summary className="text-sm">{d.filename}</summary><pre className="mt-2 max-h-44 overflow-auto whitespace-pre-wrap text-xs">{d.text.slice(0,8000)}</pre><p className="mt-2 text-xs">{t('Passport candidates','সম্ভাব্য পাসপোর্ট নম্বর')}: {d.passportNumbers.join(', ')||'—'}</p>{d.warnings.map((w,j)=><p key={j} className="mt-1 text-xs text-amber-800">{w}</p>)}</details>)}{passportCandidates.size>1&&<p className="text-xs text-red-700">{t('Different passport-number candidates found. Human review is required.','ভিন্ন সম্ভাব্য পাসপোর্ট নম্বর পাওয়া গেছে। মানব পর্যালোচনা প্রয়োজন।')}</p>}<button className="btn" onClick={()=>{setView('letter');setTab('cases');}}>{t('Review cover-letter draft','কভার লেটারের খসড়া পর্যালোচনা')}</button><p className="text-xs leading-5 text-zinc-500">{t('Extraction is not certification. OCR names, identifiers and dates remain candidates until reviewed.','তথ্য সংগ্রহ প্রত্যয়ন নয়। OCR-এর নাম, নম্বর ও তারিখ পর্যালোচনা না হওয়া পর্যন্ত সম্ভাব্য তথ্য।')}</p></section>}
 {current&&overview.pythonConfigured&&<section className="card space-y-3 p-5"><h3 className="text-sm font-semibold">{t('Python Playwright snapshot','Python Playwright প্রিভিউ')}</h3><button className="btn" disabled={busy} onClick={()=>void act(async()=>{if(!window.confirm(t('Create a paid read-only Cloud browser snapshot and stop it afterward?','অর্থপ্রদ শুধু-পাঠযোগ্য ক্লাউড ব্রাউজার প্রিভিউ তৈরি করে পরে বন্ধ করবেন?')))return;const out=await request<{preview:unknown}>({action:'snapshot',id:current.id,confirmed:true});setSnapshot(out.preview);})}>{t('Capture authorized preview','অনুমোদিত প্রিভিউ সংগ্রহ')}</button>{snapshot!==undefined&&<JsonViewer lang={lang} value={snapshot}/>}</section>}
 </div><div className="min-w-0 space-y-5"><section className="card p-5"><div className="no-print mb-4 flex flex-wrap gap-2">{(['form','checklist','letter'] as const).map(id=><button key={id} className={`btn ${view===id?'primary':''}`} onClick={()=>setView(id)}>{id==='form'?t('Form preview','ফর্ম প্রিভিউ'):id==='checklist'?t('Structural checklist','নথির চেকলিস্ট'):t('Letter draft','চিঠির খসড়া')}</button>)}</div>
 {view==='form'?<dl className="space-y-3 text-sm"><div><dt className="text-zinc-500">{t('Applicant','আবেদনকারী')}</dt><dd>{current?.applicantName??'—'}</dd></div><div><dt className="text-zinc-500">{t('Visa pathway','ভিসার পথ')}</dt><dd>{current?.visaType??'—'}</dd></div><div><dt className="text-zinc-500">{t('Authorized portal','অনুমোদিত পোর্টাল')}</dt><dd className="break-all">{current?.portalUrl??profile.portal}</dd></div><p className="text-xs leading-5 text-zinc-500">{t('Local case preview, not proof of a submitted portal form.','এটি স্থানীয় কেস প্রিভিউ, সরকারি ফর্ম জমা দেওয়ার প্রমাণ নয়।')}</p></dl>:view==='letter'?<div><pre className="print-letter whitespace-pre-wrap font-sans text-sm leading-7">{current?draftLetter(current):t('Choose a case first.','আগে কেস নির্বাচন করুন।')}</pre><button className="no-print btn mt-4" disabled={!current} onClick={()=>window.print()}><Printer size={14}/>{t('Print / save PDF draft','প্রিন্ট / খসড়া PDF সংরক্ষণ')}</button></div>:<div className="no-print space-y-3">{profile.rules.map(rule=><label key={rule.id} className="flex items-start gap-2 text-sm leading-5"><input type="checkbox" className="mt-1" checked={current?.checklist[rule.id]??false} disabled={!current||busy} onChange={e=>void act(async()=>{if(!current)return;const out=await request<{case:VisaCase}>({action:'checklist',id:current.id,key:rule.id,value:e.target.checked});merge(out.case);})}/>{lang==='bn'?rule.bn:rule.en}</label>)}<p className="rounded-lg bg-amber-50 p-3 text-xs leading-5 text-amber-900">{t('These are pathway-specific review items, not universal legal requirements. Current official-source verification is required before use.','এগুলো ভিসা পথ অনুযায়ী পর্যালোচনার বিষয়, সর্বজনীন আইনি শর্ত নয়। ব্যবহারের আগে বর্তমান সরকারি তথ্য যাচাই করুন।')}</p>{profile.sources.map(url=><a key={url} href={url} target="_blank" rel="noopener noreferrer" className="block break-all text-xs underline">{url}</a>)}<p className="text-xs text-zinc-500">{t('Rule coverage','শর্তের যাচাই')}: {profile.verification==='partial'?t('Partially verified; recheck dates','আংশিক যাচাই; তারিখ আবার দেখুন'):t('Official verification pending','সরকারি যাচাই বাকি')}</p></div>}
 {current&&<div className="no-print mt-5 space-y-3"><div className="flex flex-wrap gap-2">{!current.run&&<button className="btn primary" disabled={busy||overview.setupRequired} onClick={()=>void act(()=>run(current))}>{t('Start research & preparation','গবেষণা ও প্রস্তুতি শুরু')}</button>}<button className="btn" disabled title={t('Requires a tested portal-specific submission adapter','পরীক্ষিত পোর্টাল-নির্দিষ্ট জমার অ্যাডাপ্টার প্রয়োজন')}>{t('Final submission locked','চূড়ান্ত জমা বন্ধ')}</button></div><p className="text-xs leading-5 text-zinc-500">{t('No approval probability is invented. Final submissions require a tested deterministic portal adapter and separate version-bound approval.','অনুমোদনের সম্ভাবনা বানানো হয় না। চূড়ান্ত জমায় পরীক্ষিত পোর্টাল অ্যাডাপ্টার এবং পৃথক সংস্করণ-নির্দিষ্ট অনুমতি প্রয়োজন।')}</p></div>}</section><div className="no-print"><JsonViewer lang={lang} value={current?.run?.result??{data:null,message:t('No verified result yet','এখনো যাচাইকৃত ফলাফল নেই')}}/></div>{current?.error&&<p role="alert" className="text-xs text-amber-800">{current.error}</p>}</div></div>}
 </div></div>}
 {newCase&&<div className="no-print fixed inset-0 z-40 flex items-center justify-center bg-zinc-900/20 p-4"><section role="dialog" aria-modal="true" aria-labelledby="new-case-heading" className="safe-bottom card max-h-[90vh] w-full max-w-lg overflow-y-auto p-6 shadow-xl"><div className="flex justify-between"><h2 id="new-case-heading" className="text-lg font-semibold">{t('New visa case','নতুন ভিসা কেস')}</h2><button aria-label="Close dialog" onClick={()=>setNewCase(false)}><X/></button></div><form className="mt-5 space-y-3" onSubmit={create}><label className="block text-sm">{t('Applicant name','আবেদনকারীর নাম')}<input className="field mt-1" required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label className="block text-sm">{t('Country','দেশ')}<select className="field mt-1" value={country} onChange={e=>{const c=e.target.value as Country;setCountry(c);setPortal(countries[c].portal);setVisaType('');}}>{Object.entries(countries).map(([id,c])=><option key={id} value={id}>{lang==='bn'?c.bn:c.name}</option>)}</select></label><label className="block text-sm">{t('Visa pathway','ভিসার পথ')}<input className="field mt-1" required maxLength={120} value={visaType} onChange={e=>setVisaType(e.target.value)}/></label><label className="block text-sm">{t('Authorized portal URL','অনুমোদিত পোর্টাল URL')}<input className="field mt-1" type="url" required value={portal} onChange={e=>setPortal(e.target.value)}/></label><label className="block text-sm">{t('Research command','গবেষণার নির্দেশ')}<textarea className="field mt-1" rows={3} maxLength={2000} value={command} onChange={e=>setCommand(e.target.value)} placeholder={t('Research current official requirements','বর্তমান সরকারি শর্ত খুঁজুন')}/></label><button className="btn primary w-full" disabled={busy}>{t('Create case — no paid run','কেস তৈরি — পেইড রান নয়')}</button></form></section></div>}
 </main>;
}
