'use client';
import {useState,useEffect} from 'react';
import {Monitor,ExternalLink,Square,ShieldCheck} from 'lucide-react';
import type {VisaCase,Language} from '@/types/visa';
export default function LiveBrowserView({item,lang,busy,onResume,onStop}:{item?:VisaCase;lang:Language;busy:boolean;onResume:(otp?:string)=>Promise<void>;onStop:()=>Promise<void>}){
 const [otp,setOtp]=useState('');useEffect(()=>setOtp(''),[item?.run?.id]);const t=(a:string,b:string)=>lang==='bn'?b:a;const live=item?.run?.liveViewUrl;const stopped=item?.run?.browserStopped||item?.run?.status==='cancelled';const checkpoint=item&&['OTP Required','Review Required'].includes(item.status);
 return <section className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-zinc-200 p-4"><h2 className="flex items-center gap-2 text-sm font-semibold"><Monitor size={16}/>{t('Live cloud browser','লাইভ ক্লাউড ব্রাউজার')}</h2><div className="flex gap-3">{live&&!stopped&&<a href={live} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer" className="flex items-center gap-1 text-xs"><ExternalLink size={13}/>{t('Open live view','লাইভ ভিউ খুলুন')}</a>}{item?.run&&!stopped&&<button className="btn" disabled={busy} onClick={()=>void onStop()}><Square size={12}/>{t('Stop & clean up','বন্ধ ও পরিষ্কার করুন')}</button>}</div></div>
 {live&&!stopped?<iframe src={live} title={t('Cloud browser live view','ক্লাউড ব্রাউজার লাইভ ভিউ')} referrerPolicy="no-referrer" allow="fullscreen" className="h-[420px] w-full border-0"/>:<div className="flex h-72 flex-col items-center justify-center px-6 text-center"><Monitor size={38} className="text-zinc-300"/><p className="mt-4 text-sm">{t('The browser appears after an approved Cloud run','অনুমোদিত ক্লাউড রান শুরু হলে ব্রাউজার দেখা যাবে')}</p><p className="mt-2 max-w-md text-xs leading-5 text-zinc-500">{t('This is an authenticated live view, not a fabricated WebRTC stream. Use Open live view if embedding is blocked.','এটি অনুমোদিত লাইভ ভিউ, বানানো WebRTC স্ট্রিম নয়। এমবেড কাজ না করলে লাইভ ভিউ লিংক খুলুন।')}</p></div>}
 {checkpoint&&!stopped&&<form role="alert" className="border-t border-amber-200 bg-amber-50 p-4" onSubmit={e=>{e.preventDefault();const code=otp;setOtp('');void onResume(item.status==='OTP Required'?code:undefined);}}><h3 className="flex items-center gap-2 text-sm font-semibold text-amber-900"><ShieldCheck size={16}/>{t('Human checkpoint','মানব পর্যালোচনার ধাপ')}</h3><p className="mt-2 text-xs leading-5 text-amber-900">{item.run?.result?.message}</p><div className="mt-3 flex flex-wrap gap-2">{item.status==='OTP Required'&&<input aria-label={t('Six-digit OTP','ছয় সংখ্যার OTP')} className="field max-w-44 font-mono tracking-widest" type="password" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))}/>}<button className="btn primary" disabled={busy||(item.status==='OTP Required'&&otp.length!==6)}>{t('Verify / resume','যাচাই / পুনরায় শুরু')}</button></div><p className="mt-2 text-xs leading-5 text-amber-800">{t('OTP uses a domain-scoped secret binding, not a prompt. Complete other authentication in the live browser.','OTP প্রম্পটে নয়, নির্দিষ্ট ডোমেইনের গোপন মান হিসেবে ব্যবহৃত হয়। অন্য লগইন লাইভ ব্রাউজারে সম্পন্ন করুন।')}</p></form>}
 <p className="border-t border-zinc-200 p-3 text-[11px] leading-5 text-zinc-500">{t('Closing this page does not stop billing. Treat live-view URLs as credentials.','পেজ বন্ধ করলে বিলিং বন্ধ হয় না। লাইভ ভিউ লিংক গোপন রাখুন।')}</p></section>;
}
