'use client';
import {useState} from 'react';
import {countries} from '@/lib/countries';
import type {VisaCase,Language} from '@/types/visa';
const bnStatus:Record<VisaCase['status'],string>={Idle:'প্রস্তুত',Running:'চলমান','OTP Required':'OTP প্রয়োজন','Review Required':'পর্যালোচনা প্রয়োজন',Success:'গবেষণা সম্পন্ন',Error:'ত্রুটি','Dispatch Unknown':'অবস্থা যাচাই প্রয়োজন'};
export default function VisaCaseQueue({cases,selected,onSelect,lang}:{cases:VisaCase[];selected?:string;onSelect:(id:string)=>void;lang:Language}){
 const [country,setCountry]=useState('all'),[status,setStatus]=useState('all');const t=(a:string,b:string)=>lang==='bn'?b:a;
 const visible=cases.filter(c=>(country==='all'||c.country===country)&&(status==='all'||c.status===status));
 return <section className="card overflow-hidden"><h2 className="border-b border-zinc-200 p-4 text-sm font-semibold">{t('Master queue','কেস তালিকা')} <span className="float-right text-zinc-400">{cases.length}</span></h2><div className="grid grid-cols-2 gap-2 p-3"><select aria-label={t('Country filter','দেশ অনুযায়ী ফিল্টার')} className="field text-xs" value={country} onChange={e=>setCountry(e.target.value)}><option value="all">{t('All countries','সব দেশ')}</option>{Object.entries(countries).map(([id,c])=><option key={id} value={id}>{lang==='bn'?c.bn:c.name}</option>)}</select><select aria-label={t('Status filter','অবস্থা অনুযায়ী ফিল্টার')} className="field text-xs" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">{t('All statuses','সব অবস্থা')}</option>{Object.keys(bnStatus).map(s=><option key={s} value={s}>{lang==='bn'?bnStatus[s as VisaCase['status']]:s}</option>)}</select></div><div className="max-h-[480px] overflow-y-auto">{visible.map(c=><button key={c.id} type="button" aria-pressed={selected===c.id} onClick={()=>onSelect(c.id)} className={`w-full border-t border-zinc-100 p-4 text-left transition hover:bg-zinc-50 ${selected===c.id?'bg-zinc-50 shadow-[inset_3px_0_0_#18181b]':''}`}><p className="text-sm font-semibold">{c.applicantName}</p><p className="mt-1 text-xs text-zinc-500">{lang==='bn'?countries[c.country].bn:countries[c.country].name} · {c.visaType}</p><p className="mt-2 truncate font-mono text-[10px] text-zinc-400">{c.portalUrl}</p><span className="badge mt-3">{lang==='bn'?bnStatus[c.status]:c.status}</span></button>)}{!visible.length&&<p className="p-5 text-sm text-zinc-500">{t('No matching cases','মিল রয়েছে এমন কেস নেই')}</p>}</div></section>;
}
