'use client';
import { useState } from 'react';
import type { VisaCase } from '@/types/visa';
import { COUNTRIES, countryProfile } from '@/lib/countries';
export default function VisaCaseQueue({ cases, selected, select, bn }: { cases: VisaCase[]; selected?: string; select: (id: string) => void; bn: boolean }) {
  const [country, setCountry] = useState('all'), [status, setStatus] = useState('all');
  const statuses: Record<string,string> = { Idle:'অপেক্ষমাণ', Running:'চলমান', 'OTP Required':'OTP প্রয়োজন', 'Review Required':'পর্যালোচনা প্রয়োজন', Success:'গবেষণা সম্পন্ন', Error:'ত্রুটি', Stopped:'বন্ধ' };
  return <section className="card"><h2 className="p-4 font-semibold">{bn ? 'ভিসা কেস তালিকা' : 'Master case queue'}</h2><div className="grid grid-cols-2 gap-2 px-4 pb-4"><select aria-label="Country filter" className="field text-xs" value={country} onChange={e=>setCountry(e.target.value)}><option value="all">{bn?'সব দেশ':'All countries'}</option>{COUNTRIES.map(c=><option key={c.code} value={c.code}>{bn?c.bn:c.name}</option>)}</select><select aria-label="Status filter" className="field text-xs" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">{bn?'সব অবস্থা':'All statuses'}</option>{Object.keys(statuses).map(s=><option key={s} value={s}>{bn?statuses[s]:s}</option>)}</select></div><div className="max-h-[500px] overflow-y-auto">{cases.filter(c=>(country==='all'||country===c.country)&&(status==='all'||status===c.status)).map(c=><button key={c.id} onClick={()=>select(c.id)} aria-pressed={selected===c.id} className={`w-full border-t border-zinc-100 p-4 text-left hover:bg-zinc-50 ${selected===c.id?'bg-zinc-50 border-l-2 border-l-zinc-900':''}`}><p className="text-sm font-semibold">{c.applicantName}</p><p className="mt-1 text-xs text-zinc-500">{bn?countryProfile(c.country).bn:countryProfile(c.country).name} · {c.visaType}</p><p className="mt-2 truncate text-[11px] text-zinc-500">{c.portalUrl}</p><span className={`mt-2 inline-block rounded-full border px-2 py-1 text-[11px] ${c.status==='Running'?'border-blue-200 text-blue-700':c.status==='Success'?'border-emerald-200 text-emerald-700':c.status==='Error'?'border-red-200 text-red-700':'border-zinc-200 text-zinc-600'}`}>{bn?statuses[c.status]:c.status}</span></button>)}{!cases.length&&<p className="p-4 text-xs text-zinc-500">{bn?'প্রথম কেস তৈরি করুন':'Create your first case'}</p>}</div></section>;
}
