import type { CountryCode } from '@/types/visa';
export interface CountryProfile {
  code: CountryCode; name: string; bn: string; portal: string; node: string; pathway: string;
  checks: { id: string; en: string; bn: string }[]; blueprints: string[]; sources: string[]; ruleStatus: 'review_required' | 'partially_verified';
}
export const COUNTRIES: CountryProfile[] = [
  { code: 'au', name: 'Australia', bn: 'অস্ট্রেলিয়া', portal: 'https://immi.homeaffairs.gov.au/', node: 'SkillSelect / ImmiAccount', pathway: 'Skilled migration', ruleStatus: 'partially_verified',
    checks: [{id:'pathway',en:'Visa subclass and occupation list confirmed',bn:'ভিসা সাবক্লাস ও পেশার তালিকা যাচাই'}, {id:'assessment',en:'Relevant skills assessment verified',bn:'প্রাসঙ্গিক দক্ষতা মূল্যায়ন যাচাই'}, {id:'english',en:'English level, component scores and test date verified',bn:'ইংরেজির স্তর, প্রতিটি স্কোর ও পরীক্ষার তারিখ যাচাই'}, {id:'points',en:'EOI points supported by evidence',bn:'প্রমাণসহ EOI পয়েন্ট যাচাই'}],
    blueprints: ['EOI points summary', 'Nomination preparation checklist'], sources: ['https://immi.homeaffairs.gov.au/help-support/meeting-our-requirements/english-language/competent-english','https://immi.homeaffairs.gov.au/help-support/meeting-our-requirements/english-language/proficient-english'] },
  { code: 'rs', name: 'Serbia', bn: 'সার্বিয়া', portal: 'https://welcometoserbia.gov.rs/', node: 'Welcome to Serbia / e-Uprava', pathway: 'Residence / work', ruleStatus: 'review_required', checks: [{id:'basis',en:'Applicable residence/work basis verified',bn:'বসবাস ও কাজের প্রযোজ্য ভিত্তি যাচাই'},{id:'company',en:'Company evidence if required by pathway',bn:'পথ অনুযায়ী কোম্পানির প্রমাণ যাচাই'},{id:'address',en:'Address and arrival-registration requirements verified',bn:'ঠিকানা ও আগমন নিবন্ধনের শর্ত যাচাই'}], blueprints: ['Residence evidence checklist', 'Address declaration draft'], sources: ['https://welcometoserbia.gov.rs/'] },
  { code: 'tr', name: 'Turkey', bn: 'তুরস্ক', portal: 'https://e-ikamet.goc.gov.tr/', node: 'e-Ikamet', pathway: 'Residence permit', ruleStatus: 'review_required', checks: [{id:'photo',en:'Current biometric photo specification verified',bn:'বর্তমান বায়োমেট্রিক ছবির শর্ত যাচাই'},{id:'insurance',en:'Insurance eligibility and coverage dates verified',bn:'বিমার যোগ্যতা ও মেয়াদ যাচাই'},{id:'address',en:'Applicable address/lease evidence verified',bn:'প্রযোজ্য ঠিকানা ও ভাড়ার প্রমাণ যাচাই'}], blueprints: ['Residence preparation sheet', 'Lease evidence checklist'], sources: ['https://e-ikamet.goc.gov.tr/'] },
  { code: 'sg', name: 'Singapore', bn: 'সিঙ্গাপুর', portal: 'https://www.mom.gov.sg/', node: 'MOM / myMOM', pathway: 'Employment Pass', ruleStatus: 'partially_verified', checks: [{id:'salary',en:'Salary threshold by age, sector and effective date verified',bn:'বয়স, খাত ও কার্যকর তারিখ অনুযায়ী বেতন যাচাই'},{id:'compass',en:'COMPASS points or exemption verified',bn:'COMPASS পয়েন্ট বা ছাড় যাচাই'},{id:'degree',en:'Qualification verification if claiming C2 points',bn:'C2 পয়েন্ট দাবি করলে শিক্ষাগত যাচাই'},{id:'employer',en:'Employer and advertising requirements reviewed',bn:'নিয়োগকর্তা ও বিজ্ঞাপনের শর্ত পর্যালোচনা'}], blueprints: ['EP evidence sheet', 'Employer declaration draft'], sources: ['https://www.mom.gov.sg/passes-and-permits/employment-pass/eligibility'] },
  { code: 'ru', name: 'Russia', bn: 'রাশিয়া', portal: 'https://www.gosuslugi.ru/', node: 'Gosuslugi / competent immigration authority', pathway: 'HQS / work', ruleStatus: 'review_required', checks: [{id:'hqs',en:'Applicable HQS category and current requirements verified',bn:'প্রযোজ্য HQS শ্রেণি ও বর্তমান শর্ত যাচাই'},{id:'translation',en:'Required certified translations reviewed',bn:'প্রয়োজনীয় প্রত্যয়িত অনুবাদ পর্যালোচনা'},{id:'sponsor',en:'Employer invitation and insurance requirements verified',bn:'নিয়োগকর্তার আমন্ত্রণ ও বিমার শর্ত যাচাই'}], blueprints: ['Invitation preparation checklist', 'Translation register'], sources: ['https://www.gosuslugi.ru/'] },
  { code: 'my', name: 'Malaysia', bn: 'মালয়েশিয়া', portal: 'https://esd.imi.gov.my/', node: 'ESD / Xpats Gateway', pathway: 'Employment Pass', ruleStatus: 'review_required', checks: [{id:'category',en:'Pass category and effective salary threshold verified',bn:'পাসের শ্রেণি ও কার্যকর বেতনের সীমা যাচাই'},{id:'endorsement',en:'Relevant sector endorsement, if applicable',bn:'প্রযোজ্য খাতের অনুমোদন যাচাই'},{id:'employer',en:'Employer and qualification evidence reviewed',bn:'নিয়োগকর্তা ও যোগ্যতার প্রমাণ পর্যালোচনা'}], blueprints: ['ESD evidence checklist', 'Employer declaration draft'], sources: ['https://esd.imi.gov.my/'] },
  { code: 'sa', name: 'Saudi Arabia', bn: 'সৌদি আরব', portal: 'https://www.qiwa.sa/', node: 'Qiwa / Muqeem / competent visa service', pathway: 'Employment', ruleStatus: 'review_required', checks: [{id:'occupation',en:'Occupation classification and sponsor authorization verified',bn:'পেশার শ্রেণি ও স্পনসরের অনুমোদন যাচাই'},{id:'contract',en:'Applicable employment contract reviewed',bn:'প্রযোজ্য চাকরির চুক্তি পর্যালোচনা'},{id:'medical',en:'Medical and attestation requirements verified',bn:'চিকিৎসা ও সত্যায়নের শর্ত যাচাই'}], blueprints: ['Employment evidence pack', 'Medical evidence register'], sources: ['https://www.qiwa.sa/'] },
  { code: 'bh', name: 'Bahrain', bn: 'বাহরাইন', portal: 'https://www.lmra.gov.bh/', node: 'LMRA', pathway: 'Work permit', ruleStatus: 'review_required', checks: [{id:'cr',en:'Sponsor commercial registration verified',bn:'স্পনসরের বাণিজ্যিক নিবন্ধন যাচাই'},{id:'localization',en:'Applicable employer localization requirements verified',bn:'প্রযোজ্য স্থানীয় কর্মসংস্থানের শর্ত যাচাই'},{id:'wps',en:'Applicable wage-protection obligations reviewed',bn:'প্রযোজ্য মজুরি সুরক্ষার দায়িত্ব পর্যালোচনা'}], blueprints: ['Work permit preparation sheet', 'Sponsor evidence checklist'], sources: ['https://www.lmra.gov.bh/'] }
];
export function countryProfile(code: CountryCode): CountryProfile {
  const result = COUNTRIES.find(item => item.code === code);
  if (!result) throw new Error('Unsupported country');
  return result;
}
