import type { Country, VisaCase } from '@/types/visa';
export interface CountryProfile { name:string; bn:string; portal:string; gateway:string; rules:{id:string; en:string; bn:string}[]; verification:'partial'|'pending'; sources:string[] }
const r=(id:string,en:string,bn:string)=>({id,en,bn});
export const countries:Record<Country,CountryProfile>={
 au:{name:'Australia',bn:'অস্ট্রেলিয়া',portal:'https://immi.homeaffairs.gov.au/',gateway:'SkillSelect / ImmiAccount',verification:'partial',sources:['https://immi.homeaffairs.gov.au/help-support/meeting-our-requirements/english-language/competent-english','https://immi.homeaffairs.gov.au/help-support/meeting-our-requirements/english-language/proficient-english'],rules:[r('pathway','Confirm subclass, occupation list and assessing authority','ভিসা সাবক্লাস, পেশার তালিকা ও মূল্যায়ন কর্তৃপক্ষ যাচাই'),r('assessment','Valid skills assessment for the selected pathway','নির্বাচিত পথের জন্য বৈধ দক্ষতা মূল্যায়ন'),r('english','English thresholds selected by subclass, test and test date; IELTS 7 is not universal','সাবক্লাস, পরীক্ষা ও তারিখ অনুযায়ী ইংরেজির মান; IELTS ৭ সবার জন্য বাধ্যতামূলক নয়'),r('points','Evidence-backed EOI points and nomination review','প্রমাণভিত্তিক EOI পয়েন্ট ও মনোনয়ন পর্যালোচনা')]},
 rs:{name:'Serbia',bn:'সার্বিয়া',portal:'https://welcometoserbia.gov.rs/',gateway:'Welcome to Serbia / eUprava',verification:'pending',sources:['https://welcometoserbia.gov.rs/'],rules:[r('pathway','Verify visa/residence pathway on the official service','সরকারি সেবায় ভিসা ও আবাসনের পথ যাচাই'),r('business','Business registration and funds evidence where applicable','প্রযোজ্য ব্যবসার নিবন্ধন ও অর্থের প্রমাণ'),r('address','Address registration and lease evidence review','ঠিকানা নিবন্ধন ও লিজের প্রমাণ পর্যালোচনা'),r('forms','Use current official D-visa / residence forms','বর্তমান সরকারি D-ভিসা ও আবাসন ফর্ম ব্যবহার')]},
 tr:{name:'Türkiye',bn:'তুরস্ক',portal:'https://e-ikamet.goc.gov.tr/',gateway:'e-Ikamet',verification:'pending',sources:['https://e-ikamet.goc.gov.tr/'],rules:[r('pathway','Verify residence category and official checklist','আবাসনের ধরন ও সরকারি চেকলিস্ট যাচাই'),r('photo','Review current biometric photo specifications','বর্তমান বায়োমেট্রিক ছবির শর্ত পর্যালোচনা'),r('insurance','Review insurance applicability and coverage dates','বীমার প্রযোজ্যতা ও মেয়াদ পর্যালোচনা'),r('address','Review address, lease and notarization requirements','ঠিকানা, লিজ ও নোটারির শর্ত পর্যালোচনা')]},
 sg:{name:'Singapore',bn:'সিঙ্গাপুর',portal:'https://www.mom.gov.sg/',gateway:'MOM / myMOM',verification:'partial',sources:['https://www.mom.gov.sg/passes-and-permits/employment-pass/eligibility'],rules:[r('salary','Age/sector/effective-date EP qualifying salary verified','বয়স, খাত ও কার্যকর তারিখ অনুযায়ী EP বেতন যাচাই'),r('compass','COMPASS score and exemptions verified; missing employer data stays unknown','COMPASS ও অব্যাহতি যাচাই; নিয়োগকর্তার তথ্য না থাকলে অজানা'),r('degree','Qualification evidence if claiming C2 points; approved verification options','C2 পয়েন্ট দাবি করলে শিক্ষাগত প্রমাণ ও অনুমোদিত যাচাই'),r('employer','Employer authorization and FCF advertising applicability','নিয়োগকর্তার অনুমতি ও FCF বিজ্ঞাপনের প্রযোজ্যতা')]},
 ru:{name:'Russia',bn:'রাশিয়া',portal:'https://www.gosuslugi.ru/',gateway:'Gosuslugi / competent authority',verification:'pending',sources:['https://www.gosuslugi.ru/'],rules:[r('pathway','Verify correct HQS/work-permit authority and current route','HQS ও কাজের অনুমতির কর্তৃপক্ষ এবং বর্তমান পথ যাচাই'),r('employer','Employer eligibility and invitation evidence','নিয়োগকর্তার যোগ্যতা ও আমন্ত্রণের প্রমাণ'),r('translation','Review certified translations and identity consistency','অনুমোদিত অনুবাদ ও পরিচয়ের মিল পর্যালোচনা'),r('medical','Review applicable insurance and medical requirements','প্রযোজ্য বীমা ও চিকিৎসার শর্ত পর্যালোচনা')]},
 my:{name:'Malaysia',bn:'মালয়েশিয়া',portal:'https://esd.imi.gov.my/',gateway:'ESD / Xpats Gateway',verification:'pending',sources:['https://esd.imi.gov.my/'],rules:[r('category','Verify current pass category and salary effective dates','বর্তমান পাসের ধরন ও বেতনের কার্যকর তারিখ যাচাই'),r('employer','ESD employer registration and authorization','ESD নিয়োগকর্তার নিবন্ধন ও অনুমতি'),r('endorsement','Sector endorsement only where applicable, not universally MDEC','প্রযোজ্য খাতের অনুমোদন; MDEC সবার জন্য নয়'),r('academic','Academic and corporate-document consistency review','শিক্ষা ও প্রতিষ্ঠানের নথির সামঞ্জস্য পর্যালোচনা')]},
 sa:{name:'Saudi Arabia',bn:'সৌদি আরব',portal:'https://www.qiwa.sa/',gateway:'Qiwa / Muqeem / competent visa service',verification:'pending',sources:['https://www.qiwa.sa/'],rules:[r('occupation','Verify profession classification and authority requirements','পেশার শ্রেণি ও কর্তৃপক্ষের শর্ত যাচাই'),r('employer','Employer authorization and applicable attestations','নিয়োগকর্তার অনুমতি ও প্রযোজ্য সত্যায়ন'),r('contract','Review job-contract facts against applicant records','আবেদনকারীর তথ্যের সাথে চাকরির চুক্তি পর্যালোচনা'),r('medical','Use authorized medical records; never fabricate certification','অনুমোদিত চিকিৎসা নথি; কোনো সনদ বানানো যাবে না')]},
 bh:{name:'Bahrain',bn:'বাহরাইন',portal:'https://www.lmra.gov.bh/',gateway:'LMRA',verification:'pending',sources:['https://www.lmra.gov.bh/'],rules:[r('employer','Verify CR and employer authorization','CR ও নিয়োগকর্তার অনুমতি যাচাই'),r('localization','Review applicable Bahrainisation requirements','প্রযোজ্য বাহরাইনকরণ শর্ত পর্যালোচনা'),r('wps','Review applicable WPS requirements','প্রযোজ্য WPS শর্ত পর্যালোচনা'),r('worker','Worker identity, accommodation and official form review','কর্মীর পরিচয়, আবাসন ও সরকারি ফর্ম পর্যালোচনা')]}
};
export function validatePortal(value:string,allowlist:string):string {const u=new URL(value); if(u.protocol!=='https:'||u.username||u.password||(u.port&&u.port!=='443'))throw new Error('INVALID_PORTAL');const hosts=allowlist.split(',').map(x=>x.trim().toLowerCase());if(!hosts.includes(u.hostname.toLowerCase()))throw new Error('PORTAL_NOT_ALLOWED');return u.hostname;}
export function draftLetter(c:VisaCase):string{return `DRAFT — FOR HUMAN REVIEW, NOT AN OFFICIAL FORM\n\nTo the Visa / Immigration Officer\n\nSubject: ${c.visaType} — ${c.applicantName}\n\nI request consideration of my application for the selected ${countries[c.country].name} pathway. The facts and supporting documents must be checked by the applicant and authorized representative before this draft is used.\n\nResearch / preparation request:\n${c.command}\n\nEvidence attached for review:\n${c.documents.length?c.documents.map(d=>'- '+d.filename).join('\n'):'No supporting documents have been uploaded.'}\n\nNo employment, funds, eligibility, certification or approval is asserted by this draft. Replace this review note with verified applicant-specific facts before signing.\n\nApplicant: ${c.applicantName}\nSignature: to be provided by the applicant after review.`;}
